### ISSUE TITLE
Fix some accessibility issues

### ISSUE THREAD

**Issue by emanuelgsouza** [mvfsillva/dialetus#116]
I performed two tools to Accessibility: Google Chrome Audits and [axe](https://www.deque.com/axe/).

Problems that I found:
* Missing `title` element (can be a default value and change when region change)
* Search `input` do not have a `label` associated to it
* `html` element do not have a `lang` attribute

**Comment by mvfsillva** [comment]
Thanks, @emanuelgsouza, is very important for the project and my friend @brunopulis can help you here
