### ISSUE TITLE
Change the URL when we enter a specific dialect

### ISSUE THREAD

**Issue by mvfsillva** [mvfsillva/dialetus#132]
I think it would be better to also change the URL when we enter a specific dialect, for example:
```sh
dialetus.com/baianes
dialetus.com/mineires
```

_Originally posted by @mvfsillva in https://github.com/mvfsillva/dialetus/pull/123#issuecomment-540053672_

**Comment by manikkalai-kannan** [comment]
i will take that up

**Comment by mvfsillva** [comment]
Thanks @manikkalai-kannan 
![](https://media.giphy.com/media/35PYDhkVkOPEEAKzkc/giphy.gif)
