### ISSUE TITLE
Each word have a synonyms

### ISSUE THREAD

**Issue by emanuelgsouza** [mvfsillva/dialetus#52]
For each word, have a synonym section. For example: in the "Carioques" section, the word "Bolado" would have a synonymous word, "Chateado".

**Comment by mvfsillva** [comment]
Hi @emanuelgsouza, could transfer this issue to [dialetus-service](https://github.com/mvfsillva/dialetus-service)?

**Comment by emanuelgsouza** [comment]
Ok, I will close this issue.
