### ISSUE TITLE
Add page about the project 

### ISSUE THREAD

**Issue by brunopulis** [mvfsillva/dialetus#64]
I was thinking that it would be ideal to put a link that would lead to an "About" page of the project. People who are not developers can get lost. Adding this feature would be very interesting.

**Comment by mvfsillva** [comment]
Hi @brunopulis, I imagine it's a great idea, could you send me a proposal?

**Comment by mvfsillva** [comment]
Hey @brunopulis do you still think about doing this?

**Comment by brunopulis** [comment]
@mvfsillva yep.
